CREATE DATABASE WALLPIC;

CREATE TABLE USERS (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
lastName VARCHAR (100) NOT NULL, 
email VARCHAR (100) NOT NULL, 
password VARCHAR (50) NOT NULL,
newsletter TINYINT NOT NULL,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
deletedAt DATETIME
);
CREATE TABLE CATEGORIES (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL
);
CREATE TABLE PRICE (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
price DECIMAL(6,2) NOT NULL
);
CREATE TABLE SIZE (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
size VARCHAR (50) NOT NULL,
priceId INT UNSIGNED,
FOREIGN KEY(priceId) REFERENCES PRICE(id)
);
CREATE TABLE COLOR (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
color VARCHAR (50) NOT NULL
);

CREATE TABLE PRODUCTS (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
description TEXT NOT NULL,
images VARCHAR (100) NOT NULL,
categoryId INT UNSIGNED,
sizeId INT UNSIGNED,
colorId INT UNSIGNED,
FOREIGN KEY (categoryId) REFERENCES CATEGORIES (id),
FOREIGN KEY (sizeId) REFERENCES SIZE (id),
FOREIGN KEY (colorId) REFERENCES COLOR (id)
)





 





